project_id = "kwtvfjrrrkvdtydarfni"

[functions.send-contact-email]
verify_jwt = false

[functions.send-booking-email]
verify_jwt = false

[functions.send-application-email]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false
